### ISSUE TITLE
packages/core/package.json 似乎缺少 v8-compile-cache？

### ISSUE THREAD

**Issue by SK-Luffa** [FE-Struggler/doctor#2]
<img width="381" alt="image" src="https://github.com/BoyYangzai/doctor/assets/52227746/bd011da1-6cb0-432f-977b-89ccca6c3b62">
<img width="538" alt="image" src="https://github.com/BoyYangzai/doctor/assets/52227746/7bcb33c0-4cb2-4a9e-8b23-2ec9ac0cb3be">

**Comment by BoyYangzai** [comment]
是的 幽灵依赖了
锁在 `"v8-compile-cache": "2.3.0"`
