### ISSUE TITLE
npm run doctor:webtools 时似乎无法运行成功

### ISSUE THREAD

**Issue by SK-Luffa** [FE-Struggler/doctor#31]
npm显示core解析失败

<img width="1019" alt="image" src="https://github.com/FE-Struggler/doctor/assets/52227746/d2afef90-094c-4876-85c9-30d702743e7c">

**Comment by BoyYangzai** [comment]
已经解决～

**Comment by MiJiaCoding** [comment]
能不能在评论中稍微写一下排查的思路 和解决的方法0.0 （

**Comment by BoyYangzai** [comment]
> 能不能在评论中稍微写一下排查的思路 和解决的方法0.0 （

这里的原因 是 core 的一个 bug ～
已经 fix了
