### ISSUE TITLE
packages/core/bin/doctor.js 在没有dist文件夹的情况下进行访问

### ISSUE THREAD

**Issue by SK-Luffa** [FE-Struggler/doctor#4]
<img width="342" alt="image" src="https://github.com/BoyYangzai/doctor/assets/52227746/a0564ed1-5bc3-4e13-8608-644be7dd0570">，这里的前置条件是运行了npm run build. 需要在文档中进行说明

**Comment by BoyYangzai** [comment]
这个是常识哈 贡献指南里有写
```sh
pnpm i
npm run build:all //这个命令就可
```
