### ISSUE TITLE
pnpm7 安装依赖结构存在问题，导致后续操作无法进行

### ISSUE THREAD

**Issue by CoderSerio** [FE-Struggler/doctor#9]
<h3>复现步骤</h3>
在Node v16下使用pnpm安装依赖，会导致后续操作报错：

![image](https://github.com/FE-Struggler/doctor/assets/79406469/2734b612-9816-41bc-8717-a856984c9a13)

<h3>配置信息</h3>

Environment | Info
-- | --
System | windows11
Node.js | v16.19.0

**Comment by CoderSerio** [comment]
根据 @BoyYangzai  的建议，可以使用下面两种办法解决：
1. 锁定 node 版本 在 18+ 
2. readme 加入提示

**Comment by BoyYangzai** [comment]
@CoderSerio 不推荐使用 `engine` 字段去做限制～

**Comment by CoderSerio** [comment]
> @CoderSerio 不推荐使用 `engine` 字段去做限制～

明白了捏，我想到了一个方案，稍后我尝试一下
